# Generated by Django 4.2.4 on 2025-03-13 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('nickname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('place_of_residence', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('date_birth', models.DateField(blank=True, default=None, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
