# Generated by Django 4.1.2 on 2025-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_profile_overall_tone_skeletalmusclesystem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentaljawsystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='digestivesystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='endocrinesystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='excretorysystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='hematopoieticmetabolicsystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='immunesystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='mentalhealthsystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='respiratorysystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sensorysystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skeletalmusclesystem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Overall_tone',
        ),
        migrations.AddField(
            model_name='profile',
            name='heath_system',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CardiovascularSystem',
        ),
        migrations.DeleteModel(
            name='DentalJawSystem',
        ),
        migrations.DeleteModel(
            name='DigestiveSystem',
        ),
        migrations.DeleteModel(
            name='EndocrineSystem',
        ),
        migrations.DeleteModel(
            name='ExcretorySystem',
        ),
        migrations.DeleteModel(
            name='HematopoieticMetabolicSystem',
        ),
        migrations.DeleteModel(
            name='ImmuneSystem',
        ),
        migrations.DeleteModel(
            name='MentalHealthSystem',
        ),
        migrations.DeleteModel(
            name='RespiratorySystem',
        ),
        migrations.DeleteModel(
            name='SensorySystem',
        ),
        migrations.DeleteModel(
            name='SkeletalMuscleSystem',
        ),
    ]
