# Generated by Django 4.1.2 on 2025-03-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_dentaljawsystem_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='heath_system',
            new_name='health_system',
        ),
    ]
