# Generated by Django 4.1.2 on 2025-03-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_heath_system_profile_health_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='health_system',
            field=models.JSONField(default=None),
        ),
    ]
