# Generated by Django 4.1.2 on 2025-03-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_profile_health_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='health_system',
            field=models.JSONField(default=None, null=True),
        ),
    ]
