# Generated by Django 4.1.2 on 2025-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_profile_health_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='life_expectancy',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
