# Generated by Django 4.1.2 on 2025-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_categories_quest_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
