# Generated by Django 4.2.4 on 2025-03-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_quest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
