# Generated by Django 4.2.4 on 2025-03-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_quest_message_quest_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='read',
        ),
        migrations.CreateModel(
            name='tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('message', models.TextField(default=None, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
    ]
