# Generated by Django 4.1.2 on 2025-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
