# Generated by Django 4.1.2 on 2025-06-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_profile_photo_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking_Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('check_is', models.BooleanField(default=None, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_tracking', to='backend.habit')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
    ]
