# Generated by Django 4.1.2 on 2025-06-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_tracking_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_is', models.CharField(max_length=150)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('place_of_residence', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('date_birth', models.DateField(blank=True, default=None, null=True)),
                ('health_system', models.JSONField(default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
    ]
