# Generated by Django 4.1.2 on 2025-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
