# Generated by Django 4.1.2 on 2025-06-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_relationship_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catigories', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('time_day', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('intake', models.CharField(max_length=200)),
                ('notification', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
    ]
