# Generated by Django 4.1.2 on 2025-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_drugs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
