# Generated by Django 4.1.2 on 2025-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_check_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='interval',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
