# Generated by Django 4.1.2 on 2025-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_drugs_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='notification',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='time_day',
            field=models.IntegerField(),
        ),
    ]
