# Generated by Django 4.1.2 on 2025-06-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_drugs_day_alter_drugs_notification_and_more'),
    ]

    operations = [
    ]
