# Generated by Django 4.1.2 on 2025-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_populate_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family_ref',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ref',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='notification',
            field=models.JSONField(),
        ),
    ]
