# Generated by Django 4.1.2 on 2025-06-05 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_profile_family_ref_profile_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_ref',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
