# Generated by Django 4.1.2 on 2025-06-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_profile_recommended_by_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_by_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_system_family', to='backend.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_is',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
