# Generated by Django 4.1.2 on 2025-06-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_profile_recommended_by_family_profile_who_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_family', to='backend.profile'),
        ),
    ]
