# Generated by Django 4.1.2 on 2025-06-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_profile_family'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
