# Generated by Django 4.1.2 on 2025-06-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_delete_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_check', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
    ]
