# Generated by Django 4.1.2 on 2025-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_daily_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_check',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
