# Generated by Django 4.1.2 on 2025-06-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_daily_check_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentgen', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.AlterField(
            model_name='check_drugs',
            name='drugs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs_check', to='backend.drugs', verbose_name='Drugs'),
        ),
        migrations.CreateModel(
            name='Rentgen_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentgen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentgen_image', to='backend.rentgen', verbose_name='Rentgen')),
            ],
        ),
    ]
