# Generated by Django 4.1.2 on 2025-06-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_rentgen_alter_check_drugs_drugs_rentgen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentgen',
            name='answer',
            field=models.TextField(default=None, null=True),
        ),
    ]
