# Generated by Django 4.1.2 on 2025-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_rentgen_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentgen_image',
            name='images',
            field=models.ImageField(default=None, upload_to='rentgen/'),
        ),
    ]
