# Generated by Django 4.1.2 on 2025-06-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_rentgen_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentgen',
            name='message',
            field=models.TextField(default='', null=True),
        ),
    ]
