# Generated by Django 4.1.2 on 2025-06-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_alter_rentgen_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentgen',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
