# Generated by Django 4.1.2 on 2025-06-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_rentgen_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klichka', models.CharField(max_length=200)),
                ('pet', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('health_system', models.JSONField(default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
    ]
