# Generated by Django 4.1.2 on 2025-06-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('detail', models.JSONField(default=None, null=True)),
                ('total', models.JSONField(default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
    ]
