# Generated by Django 4.1.2 on 2025-06-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default=None, null=True)),
                ('answer', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='backend.pet', verbose_name='Питомец')),
            ],
        ),
    ]
