# Generated by Django 4.1.2 on 2025-06-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_petchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catigories', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('time_day', models.IntegerField()),
                ('day', models.IntegerField()),
                ('intake', models.CharField(max_length=200)),
                ('interval', models.DurationField(blank=True, null=True)),
                ('notification', models.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_drugs', to='backend.pet', verbose_name='Питомец')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Check_Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('drugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_drugs_check', to='backend.pet_drugs', verbose_name='Drugs')),
            ],
        ),
    ]
