# Generated by Django 4.1.2 on 2025-06-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_pet_drugs_pet_check_drugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetRentgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('answer', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentgen_pet', to='backend.pet', verbose_name='Питомец')),
            ],
        ),
        migrations.CreateModel(
            name='PetRentgen_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default=None, upload_to='rentgen/')),
                ('rentgen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_rentgen_image', to='backend.petrentgen', verbose_name='Rentgen')),
            ],
        ),
        migrations.CreateModel(
            name='PetDaily_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_daily_check', to='backend.pet', verbose_name='Питомец')),
            ],
        ),
    ]
