# Generated by Django 4.1.2 on 2025-06-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_petrentgen_petrentgen_image_petdaily_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petrentgen',
            old_name='profile',
            new_name='pet',
        ),
    ]
