# Generated by Django 4.1.2 on 2025-06-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_rename_profile_petrentgen_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrentgen_image',
            name='rentgen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentgen_image', to='backend.petrentgen', verbose_name='Rentgen'),
        ),
    ]
