# Generated by Django 4.1.2 on 2025-06-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_alter_petrentgen_image_rentgen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petdaily_check',
            old_name='profile',
            new_name='pet',
        ),
    ]
