# Generated by Django 4.1.2 on 2025-06-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_rename_profile_petdaily_check_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IK',
            field=models.FloatField(null=True),
        ),
    ]
