# Generated by Django 4.1.2 on 2025-06-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_profile_ik'),
    ]

    operations = [
        migrations.AddField(
            model_name='calories',
            name='answer',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='calories',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to='calories/'),
        ),
    ]
