# Generated by Django 4.1.2 on 2025-06-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_calories_answer_calories_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('detail', models.JSONField(default=None, null=True)),
                ('total', models.JSONField(default=None, null=True)),
                ('images', models.ImageField(default=None, null=True, upload_to='calories/')),
                ('answer', models.TextField(default=None, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_calories', to='backend.pet', verbose_name='Питомец')),
            ],
        ),
    ]
