# Generated by Django 4.1.2 on 2025-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_petcalories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
    ]
