# Generated by Django 4.1.2 on 2025-07-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_profile_smoke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='smoke',
        ),
    ]
