# Generated by Django 4.1.2 on 2025-07-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_remove_profile_smoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
