# Generated by Django 4.2.4 on 2026-03-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_habit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='IK',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='life_expectancy',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
