# Generated by Django 4.2.4 on 2026-04-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_profile_telegram_id_alter_profile_ik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
    ]
