# Generated by Django 4.1.2 on 2026-04-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Система организма')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Подраздел (орган)')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='backend.healthsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание для пользователя')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='backend.subsection')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('slider', 'Слайдер (Плохо - Хорошо)'), ('binary', 'Да/Нет'), ('radio', 'Одиночный выбор'), ('emoji', 'Смайлики')], default='radio', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='backend.test')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Вариант ответа')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы за этот ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='backend.question')),
            ],
        ),
    ]
