# Generated by Django 4.1.2 on 2026-04-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_healthsystem_subsection_test_question_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthsystem',
            options={'verbose_name': 'Система организма', 'verbose_name_plural': '1. Системы организма'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': 'Подраздел', 'verbose_name_plural': '2. Подразделы (Органы)'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': '3. Тесты'},
        ),
        migrations.AlterField(
            model_name='subsection',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='backend.healthsystem', verbose_name='Подраздел (орган)'),
        ),
    ]
