# Generated by Django 4.2.4 on 2026-04-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_alter_healthsystem_options_alter_subsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='backend.subsection', verbose_name='Подраздел (орган)'),
        ),
    ]
