# Generated by Django 4.2.4 on 2026-04-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_alter_test_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('slider', 'Слайдер (Плохо - Хорошо)'), ('binary', 'Да/Нет'), ('radio', 'Одиночный выбор'), ('emoji', 'Смайлики'), ('text', 'Текстовый ответ (Поле ввода)')], default='radio', max_length=20),
        ),
    ]
