# Generated by Django 4.2.4 on 2026-04-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
