# Generated by Django 4.2.4 on 2026-04-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_remove_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_drugs',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='drugs',
            name='notification',
        ),
        migrations.AddField(
            model_name='check_drugs',
            name='is_taken',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Notification_drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('drugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_drugs', to='backend.drugs')),
            ],
        ),
        migrations.AddField(
            model_name='check_drugs',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='backend.notification_drugs'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='check_drugs',
            unique_together={('notification', 'date')},
        ),
        migrations.RemoveField(
            model_name='check_drugs',
            name='drugs',
        ),
        migrations.RemoveField(
            model_name='check_drugs',
            name='profile',
        ),
    ]
