# Generated by Django 4.2.4 on 2026-04-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_rename_created_at_check_drugs_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_drugs',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
