# Generated by Django 4.2.4 on 2026-05-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_alter_notification_drugs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calories',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
