# Generated by Django 4.2.4 on 2026-05-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_calories_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calories',
            name='answer',
        ),
    ]
