# Generated by Django 4.2.4 on 2026-05-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_remove_calories_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(default=0)),
                ('proteins', models.PositiveIntegerField(default=0)),
                ('fats', models.PositiveIntegerField(default=0)),
                ('carbs', models.PositiveIntegerField(default=0)),
                ('fiber', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to='backend.profile')),
            ],
        ),
    ]
