# Generated by Django 4.2.4 on 2026-05-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_nutritiongoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentgen_image',
            name='images',
            field=models.FileField(default=None, upload_to='rentgen/'),
        ),
    ]
