# Generated by Django 4.2.4 on 2026-05-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_alter_rentgen_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='system',
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='test',
            name='role',
            field=models.CharField(choices=[('human', 'Человек'), ('baby', 'Ребенок'), ('animal', 'Животное')], default='human', max_length=20, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='test',
            name='system',
            field=models.CharField(choices=[('others', '📁 Другие'), ('tonus', 'Общий тонус'), ('respiratory', 'Дыхательная система'), ('cardio', 'Сердечно-сосудистая система'), ('skeletal', 'Опорно-двигательный аппарат'), ('endocrine', 'Эндокринная система'), ('digestive', 'Пищеварительная система'), ('reproductive', 'Половая система'), ('nervous', 'Нервная система'), ('excretory', 'Выделительная система'), ('dental', 'Зубочелюстная система'), ('sensory', 'Органы чувств'), ('hematopoietic', 'Органы кроветворения'), ('immune', 'Иммунная система'), ('psychological', 'Психологическое состояние')], default='others', max_length=50, verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='test',
            name='subsection',
            field=models.CharField(blank=True, choices=[('lungs', 'Легкие'), ('trachea', 'Трахея'), ('nasopharynx', 'Носоглотка'), ('bronchi', 'Бронхи'), ('ribs', 'Рёбра'), ('diaphragm', 'Диафрагма'), ('pulse', 'Пульс'), ('systolic', 'Систолическое давление'), ('diastolic', 'Диастолическое давление'), ('skeleton', 'Скелет'), ('muscles', 'Мышцы'), ('spine', 'Позвоночник'), ('testicles', 'Тестикулы'), ('prostate', 'Простата'), ('hormonal', 'Гормональная система'), ('function', 'Функциональность'), ('esophagus', 'Пищевод'), ('liver', 'Печень'), ('stomach', 'Желудок')], max_length=50, null=True, verbose_name='Подраздел (необязательно)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='HealthSystem',
        ),
        migrations.DeleteModel(
            name='Subsection',
        ),
    ]
