# Generated by Django 4.2.4 on 2026-05-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_remove_subsection_system_alter_test_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='which_animal',
            field=models.CharField(blank=True, choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('cow', 'Корова'), ('horse', 'Лошадь'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Какое животное'),
        ),
    ]
