# Generated by Django 4.2.4 on 2026-05-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_test_which_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
    ]
