# Generated by Django 4.2.4 on 2026-05-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_remove_choice_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddField(
            model_name='test',
            name='example_answer',
            field=models.TextField(blank=True, verbose_name='Пример ответа'),
        ),
    ]
