# Generated by Django 4.2.4 on 2026-05-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_alter_question_options_remove_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='system',
            field=models.CharField(choices=[('others', '📁 Другие'), ('respiratory', 'Дыхательная система'), ('cardio', 'Сердечно-сосудистая система'), ('skeletal', 'Опорно-двигательный аппарат'), ('endocrine', 'Эндокринная система'), ('digestive', 'Пищеварительная система'), ('reproductive', 'Половая система'), ('nervous', 'Нервная система'), ('excretory', 'Выделительная система'), ('dental', 'Зубочелюстная система'), ('sensory', 'Органы чувств'), ('hematopoietic', 'Органы кроветворения'), ('immune', 'Иммунная система'), ('psychological', 'Психологическое состояние')], default='others', max_length=50, verbose_name='Система'),
        ),
    ]
