# Generated by Django 4.2.4 on 2026-05-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_pet_photo_alter_test_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('slider', 'Слайдер (Плохо - Хорошо)'), ('binary', 'Да/Нет'), ('radio', 'Несколько вариантов'), ('text', 'Текстовый ответ (Поле ввода)')], default='radio', max_length=20),
        ),
    ]
