# Generated by Django 4.1.2 on 2026-05-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subsection',
            field=models.CharField(blank=True, choices=[('lungs', 'Легкие'), ('trachea', 'Трахея'), ('nasopharynx', 'Носоглотка'), ('bronchi', 'Бронхи'), ('ribs', 'Рёбра'), ('diaphragm', 'Диафрагма'), ('pulse', 'Пульс'), ('systolic', 'Систолическое давление'), ('diastolic', 'Диастолическое давление'), ('skeleton', 'Скелет'), ('muscles', 'Мышцы'), ('spine', 'Позвоночник'), ('testicles', 'Тестикулы'), ('prostate', 'Простата'), ('hormonal', 'Гормональная система'), ('function', 'Функциональность'), ('esophagus', 'Пищевод'), ('liver', 'Печень'), ('stomach', 'Желудок')], max_length=50, null=True, verbose_name='Подсистема'),
        ),
        migrations.AlterField(
            model_name='test',
            name='which_animal',
            field=models.CharField(blank=True, choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('rat', 'Крыса'), ('mouse', 'Мышь'), ('svinka', 'Морск.свинка'), ('xomyak', 'Хомяк'), ('shinshila', 'Шиншилла')], max_length=20, null=True, verbose_name='Вид животного'),
        ),
    ]
