# Generated by Django 4.1.2 on 2026-05-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_alter_test_subsection_alter_test_which_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_habit',
            name='created_at',
            field=models.DateField(),
        ),
    ]
