# Generated by Django 4.1.2 on 2026-05-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_alter_tracking_habit_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoalPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(default=0)),
                ('proteins', models.PositiveIntegerField(default=0)),
                ('fats', models.PositiveIntegerField(default=0)),
                ('carbs', models.PositiveIntegerField(default=0)),
                ('fiber', models.PositiveIntegerField(default=0)),
                ('vitamin', models.PositiveIntegerField(default=0)),
                ('mineral', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal_pet', to='backend.pet')),
            ],
        ),
    ]
