# Generated by Django 4.1.2 on 2026-05-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_nutritiongoalpet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petcalories',
            name='answer',
        ),
        migrations.AddField(
            model_name='petcalories',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
