# Generated by Django 4.1.2 on 2026-05-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_remove_petcalories_answer_petcalories_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_drugs',
            name='notification',
        ),
        migrations.CreateModel(
            name='Notification_Pet_drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('drugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_pet_drugs', to='backend.pet_drugs')),
            ],
        ),
    ]
