# Generated by Django 4.1.2 on 2026-05-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_remove_pet_drugs_notification_notification_pet_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_check_drugs',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pet_check_drugs',
            name='is_taken',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet_check_drugs',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='backend.notification_pet_drugs'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pet_check_drugs',
            unique_together={('notification', 'date')},
        ),
        migrations.RemoveField(
            model_name='pet_check_drugs',
            name='drugs',
        ),
    ]
