# Generated by Django 4.1.2 on 2026-05-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_pet_check_drugs_date_pet_check_drugs_is_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
