# Generated by Django 4.1.2 on 2026-05-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='tests_admin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_admin', to='backend.test'),
        ),
    ]
