# Generated by Django 4.1.2 on 2026-05-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_tests_tests_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='tests_admin',
        ),
    ]
