# Generated by Django 4.1.2 on 2026-05-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_remove_tests_tests_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests_Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('message', models.TextField(default=None, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_pet', to='backend.pet', verbose_name='Профиль')),
            ],
        ),
    ]
