# Generated by Django 4.1.2 on 2026-05-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_tests_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests_pet',
            old_name='profile',
            new_name='pet',
        ),
    ]
