# Generated by Django 4.2.4 on 2026-05-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_rename_profile_tests_pet_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='role',
            field=models.CharField(choices=[('human', 'Взрослый'), ('baby', 'Ребенок'), ('animal', 'Животное')], default='human', max_length=20, verbose_name='Роль'),
        ),
    ]
