# Generated by Django 4.2.4 on 2026-05-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
