# Generated by Django 4.1.2 on 2026-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_alter_calories_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='water_goal',
            field=models.FloatField(default=0),
        ),
    ]
