# Generated by Django 4.1.2 on 2026-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0089_profile_water_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='calories',
            name='water_intake',
            field=models.FloatField(default=0, verbose_name='Выпито воды '),
        ),
    ]
