# Generated by Django 4.1.2 on 2026-06-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0090_calories_water_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='pressure_bottom',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='pressure_top',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calories',
            name='water_intake',
            field=models.FloatField(default=0, verbose_name='Выпито воды'),
        ),
    ]
