# Generated by Django 4.1.2 on 2026-06-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_tests_pressure_bottom_tests_pressure_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='life_expectancy_json',
            field=models.JSONField(default=None, null=True),
        ),
    ]
