# Generated by Django 4.1.2 on 2026-06-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_profile_life_expectancy_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='life_expectancy_json',
            field=models.TextField(default=None, null=True),
        ),
    ]
