# Generated by Django 4.1.2 on 2026-06-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_alter_profile_life_expectancy_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_top', models.PositiveIntegerField(verbose_name='Систолическое (верхнее)')),
                ('pressure_bottom', models.PositiveIntegerField(verbose_name='Диастолическое (нижнее)')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_history', to='backend.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Давление',
                'verbose_name_plural': 'История давления',
            },
        ),
    ]
