# Generated by Django 4.1.2 on 2026-06-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0094_bloodpressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='pressure_bottom',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='pressure_top',
        ),
    ]
