# Generated by Django 4.1.2 on 2026-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0095_remove_tests_pressure_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pressure_test',
            field=models.TextField(default=None, null=True),
        ),
    ]
