# Generated by Django 4.1.2 on 2026-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0096_profile_pressure_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='health_recommendations',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='risk_test',
            field=models.TextField(default=None, null=True),
        ),
    ]
