# Generated by Django 4.1.2 on 2026-06-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0097_profile_health_recommendations_profile_risk_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diary_plus',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pressure_plus',
            field=models.TextField(default=None, null=True),
        ),
    ]
