# Generated by Django 4.1.2 on 2026-06-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_profile_diary_plus_profile_pressure_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='risk_test',
            field=models.TextField(default=None, null=True),
        ),
    ]
