# Generated by Django 4.1.2 on 2026-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_pet_risk_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcalories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
