# Generated by Django 4.1.2 on 2026-06-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0100_alter_petcalories_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='analysis_risk',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='analysis_risk',
            field=models.TextField(default=None, null=True),
        ),
    ]
