# Generated by Django 4.1.2 on 2026-06-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_pet_analysis_risk_profile_analysis_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='subsection',
            field=models.CharField(blank=True, choices=[('lungs', 'Легкие'), ('trachea', 'Трахея'), ('nasopharynx', 'Носоглотка'), ('bronchi', 'Бронхи'), ('ribs', 'Рёбра'), ('diaphragm', 'Диафрагма'), ('pulse', 'Пульс'), ('systolic', 'Систолическое давление'), ('diastolic', 'Диастолическое давление'), ('skeleton', 'Скелет'), ('muscles', 'Мышцы'), ('spine', 'Позвоночник'), ('protection', 'Защита'), ('joint_flexibility', 'Гибкость суставов'), ('cushioning', 'Амортизация'), ('thyroid', 'Щитовидная железа'), ('pineal', 'Шишковидная железа'), ('adrenals', 'Надпочечники'), ('pancreas', 'Поджелудочная железа'), ('thymus', 'Вилочковая железа'), ('gonads', 'Половые железы'), ('esophagus', 'Пищевод'), ('liver', 'Печень'), ('stomach', 'Желудок'), ('large_intestine', 'Толстый кишечник'), ('small_intestine', 'Тонкий кишечник'), ('oral_cavity', 'Ротовая полость'), ('testicles', 'Тестикулы'), ('prostate', 'Простата'), ('hormonal', 'Гормональная система'), ('function', 'Функциональность')], max_length=50, null=True, verbose_name='Подсистема'),
        ),
    ]
