# Generated by Django 4.1.2 on 2026-06-23 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_profile_height_profile_weight_alter_test_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='family_ref',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='profile',
        ),
        migrations.AddField(
            model_name='pet',
            name='profile',
            field=models.ManyToManyField(related_name='pet', to='backend.profile', verbose_name='Профиль'),
        ),
    ]
