# Generated by Django 4.1.2 on 2026-06-23 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0103_pet_family_ref_remove_pet_profile_pet_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='family_ref',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
