# Generated by Django 4.1.2 on 2026-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0104_alter_pet_family_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medical_history',
            field=models.JSONField(blank=True, default=dict, verbose_name='Медицинская карта'),
        ),
    ]
