# Generated by Django 4.1.2 on 2026-06-25 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0105_profile_medical_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='profile',
        ),
        migrations.AddField(
            model_name='pet',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='backend.profile', verbose_name='Профиль'),
            preserve_default=False,
        ),
    ]
