# Generated by Django 4.1.2 on 2026-06-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0106_remove_pet_profile_pet_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='medical_history',
            field=models.JSONField(blank=True, default=dict, verbose_name='Медицинская карта'),
        ),
    ]
