# Generated by Django 4.1.2 on 2026-06-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0107_pet_medical_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
        migrations.CreateModel(
            name='PetShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_profiles_links', to='backend.pet', verbose_name='Привязанный питомец')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_pets_links', to='backend.profile', verbose_name='Кто добавил питомца')),
            ],
            options={
                'verbose_name': 'Совместный доступ к питомцу',
                'verbose_name_plural': 'Совместный доступ к питомцам',
                'unique_together': {('profile', 'pet')},
            },
        ),
    ]
