# Generated by Django 4.1.2 on 2026-06-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0109_chat_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='family_ref',
            new_name='pet_family_ref',
        ),
    ]
