# Generated by Django 4.1.2 on 2026-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0110_rename_family_ref_pet_pet_family_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_calories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_drugs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_habit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_health',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант ответа'),
        ),
    ]
