# Generated by Django 4.1.2 on 2026-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0111_profile_notification_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='food_percentage',
            field=models.FloatField(default=100),
        ),
    ]
