# Generated by Django 4.1.2 on 2026-07-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0112_profile_food_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='food_percentage',
            field=models.FloatField(default=100),
        ),
    ]
