# Generated by Django 4.2.4 on 2026-08-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0113_pet_food_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critical_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='harmone_function',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='harmone_profile',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='harmone_prostate',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_reproductive',
            field=models.BooleanField(default=True),
        ),
    ]
