# Generated by Django 4.2.4 on 2026-08-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0114_critical_analysis_profile_harmone_function_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critical_analysis',
            options={'verbose_name': 'Kритические анализы', 'verbose_name_plural': 'Kритические анализы'},
        ),
        migrations.RemoveField(
            model_name='critical_analysis',
            name='text',
        ),
        migrations.AddField(
            model_name='critical_analysis',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='critical_analysis',
            name='example_answer',
            field=models.TextField(blank=True, verbose_name='Пример ответа'),
        ),
        migrations.AddField(
            model_name='critical_analysis',
            name='system',
            field=models.CharField(choices=[('reproductive', 'Половая система - мужчина')], default='others', max_length=50, verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='critical_analysis',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Question_critical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('slider', 'Слайдер (Плохо - Хорошо)'), ('binary', 'Да/Нет'), ('radio', 'Несколько вариантов'), ('text', 'Текстовый ответ (Поле ввода)')], default='radio', max_length=20)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='backend.critical_analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Choice_critical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='backend.critical_analysis')),
            ],
        ),
    ]
