# Generated by Django 4.2.4 on 2026-08-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0115_alter_critical_analysis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_critical',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='backend.question_critical'),
        ),
    ]
