# Generated by Django 4.2.4 on 2026-08-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0116_alter_choice_critical_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notification_reproductive',
            new_name='notification_female',
        ),
    ]
