# Generated by Django 4.2.4 on 2026-08-10 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0117_rename_notification_reproductive_profile_notification_female'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Период менструации',
                'verbose_name_plural': 'Периоды менструаций',
                'ordering': ['-start_date'],
            },
        ),
    ]
