# Generated by Django 4.2.4 on 2026-08-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0118_cycleperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycleperiod',
            name='user',
        ),
        migrations.AddField(
            model_name='cycleperiod',
            name='Profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='backend.profile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('note', models.TextField(blank=True, verbose_name='Текстовая заметка')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='backend.profile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
