# Generated by Django 4.2.4 on 2026-08-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0119_remove_cycleperiod_user_cycleperiod_profile_dailylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные опросников и тестов'),
        ),
    ]
