# Generated by Django 4.2.4 on 2026-08-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0120_dailylog_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='cycleperiod',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='dailylog',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('profile', 'created_at')},
        ),
    ]
