# Generated by Django 4.2.4 on 2026-08-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0121_alter_dailylog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='harmone_function',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='harmone_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='harmone_prostate',
        ),
        migrations.CreateModel(
            name='MenHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hormone_profile', models.TextField(verbose_name='Гормональный профиль')),
                ('hormone_function', models.TextField(verbose_name='Функциональность половой системы')),
                ('hormone_prostate', models.TextField(verbose_name='Состояние простаты и онкориски')),
                ('created_at', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='men_health', to='backend.profile')),
            ],
        ),
    ]
