# Generated by Django 4.2.4 on 2026-08-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0122_remove_profile_harmone_function_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='data',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='activities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='mood',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='pain',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='pregnancy',
            field=models.JSONField(default=dict),
        ),
    ]
