# Generated by Django 4.2.4 on 2026-08-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0123_remove_dailylog_data_dailylog_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(verbose_name='Отчет профиль')),
                ('recommendation', models.TextField(verbose_name='Рекомендация ')),
                ('created_at', models.DateField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='female_health', to='backend.profile')),
            ],
        ),
    ]
