# Generated by Django 4.2.4 on 2026-08-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0124_femalehealthprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFemale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
                ('three_days_before', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationfemale', to='backend.profile')),
            ],
        ),
    ]
