# Generated by Django 4.2.4 on 2026-08-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0125_notificationfemale'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
