# Generated by Django 4.2.4 on 2026-08-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0126_profile_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='critical_analysis',
            name='sub_section',
            field=models.CharField(choices=[('hormonal_profile', 'Гормональный профиль'), ('functionality', 'Функциональность'), ('prostate_and_oncorisks', 'Простата и онкориски'), ('critical_tests', 'Критические анализы')], default='others', max_length=50, verbose_name='Под Система'),
        ),
    ]
