# Generated by Django 4.2.4 on 2026-08-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0127_critical_analysis_sub_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='pregnancy_start',
            field=models.BooleanField(default=False),
        ),
    ]
