# Generated by Django 4.2.4 on 2026-08-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0128_dailylog_pregnancy_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='pregnancy_start',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_pregnant',
            field=models.BooleanField(default=False, verbose_name='Беременность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pregnancy_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала беременности'),
        ),
    ]
