# Generated by Django 4.2.4 on 2026-08-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0129_remove_dailylog_pregnancy_start_profile_is_pregnant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_CARDIOVASCULAR',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_DIGESTIVE',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_ENDOCRINE',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_MUSCULOSKELETAL',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_REPRODUCTIVE',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_RESPIRATORY',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
