# Generated by Django 4.2.4 on 2026-08-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0130_profile_avatar_cardiovascular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critical_analysis',
            name='sub_section',
            field=models.CharField(choices=[('critical_tests', 'Критические анализы')], default='others', max_length=50, verbose_name='Подсистема'),
        ),
    ]
