# Generated by Django 4.2.4 on 2026-08-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0131_alter_critical_analysis_sub_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critical_analysis',
            options={'verbose_name': 'Тесты Kритические анализы', 'verbose_name_plural': 'Тесты Kритические анализы'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
