# Generated by Django 4.2.4 on 2026-08-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0132_alter_critical_analysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='generated_avatars',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
