# Generated by Django 4.2.4 on 2026-09-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0133_profile_generated_avatars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_CARDIOVASCULAR',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_DIGESTIVE',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_ENDOCRINE',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_MUSCULOSKELETAL',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_REPRODUCTIVE',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_RESPIRATORY',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_image',
        ),
    ]
