# Generated by Django 4.2.4 on 2026-09-01 11:24

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0134_remove_profile_avatar_cardiovascular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', validators=[backend.validators.validate_face_photo]),
        ),
    ]
