# Generated by Django 4.2.4 on 2026-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0137_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='system_avatars',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
