# Generated by Django 4.2.4 on 2026-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0138_profile_system_avatars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
