# Generated by Django 4.1.2 on 2026-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0139_alter_tests_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_health_system',
            field=models.JSONField(default=None, null=True),
        ),
    ]
